CC = gcc
CFLAGS = -Wall -Wextra -Werror
NAME = libft.a
SRCS = ft_bzero.c ft_isalnum.c ft_isalpha.c ft_isascii.c ft_isdigit.c \
ft_isprint.c ft_memchr.c ft_calloc.c ft_strdup.c ft_substr.c ft_strjoin.c \
ft_split.c ft_strtrim.c ft_itoa.c ft_memcpy.c ft_memmove.c ft_memmove.c \
ft_memset.c ft_strchr.c ft_strlcat.c ft_strlcpy.c ft_strlen.c ft_strncmp.c \
ft_strchr.c ft_tolower.c ft_toupper.c ft_strrchr.c ft_memchr.c \
ft_strnstr.c ft_atoi.c ft_strmapi.c ft_striteri.c ft_putchar_fd.c \
ft_putstr_fd.c ft_putendl_fd.c ft_putnbr_fd.c ft_memcmp.c
OBJECTS = $(SRCS:.c=.o)
BNSSRCS = ft_lstnew_bonus.c ft_lstsize_bonus.c ft_lstadd_front_bonus.c \
ft_lstlast_bonus.c ft_lstadd_back_bonus.c ft_lstdelone_bonus.c \
ft_lstiter_bonus.c ft_lstclear_bonus.c ft_lstmap_bonus.c
BNSOBJECTS = $(BNSSRCS:.c=.o)
INC = -I./
ARRCS = ar rcsu
RMF = rm -f

all : $(NAME)

$(NAME) : $(OBJECTS)
	$(ARRCS) $(NAME) $(OBJECTS)

bonus :
	@$(MAKE) OBJECTS='$(OBJECTS) $(BNSOBJECTS)' all

%.o : %.c
	$(CC) $(CFLAGS) -c $< $(INC)

clean :
	$(RMF) $(OBJECTS) $(BNSOBJECTS)

fclean : clean
	$(RMF) $(NAME) 

re : fclean all

.PHONY : claen fclaen all re bonus